// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlhy2tQKvlx9AhQ_bwDCta72qvhdCJbP8',
    appId: '1:90441735790:web:de0e387c8352b3ad74107f',
    messagingSenderId: '90441735790',
    projectId: 'to-do-c2aee',
    authDomain: 'to-do-c2aee.firebaseapp.com',
    storageBucket: 'to-do-c2aee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqoVcGgpvu57C9kzVBo7rWpYIoWC-Iuz0',
    appId: '1:90441735790:android:dfad2cf20575838074107f',
    messagingSenderId: '90441735790',
    projectId: 'to-do-c2aee',
    storageBucket: 'to-do-c2aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqju3NkYgteSq0YYAE7Cv4OG_-AjFam6U',
    appId: '1:90441735790:ios:c7e943b052c5284974107f',
    messagingSenderId: '90441735790',
    projectId: 'to-do-c2aee',
    storageBucket: 'to-do-c2aee.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqju3NkYgteSq0YYAE7Cv4OG_-AjFam6U',
    appId: '1:90441735790:ios:c7e943b052c5284974107f',
    messagingSenderId: '90441735790',
    projectId: 'to-do-c2aee',
    storageBucket: 'to-do-c2aee.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlhy2tQKvlx9AhQ_bwDCta72qvhdCJbP8',
    appId: '1:90441735790:web:e1073b819ef594f374107f',
    messagingSenderId: '90441735790',
    projectId: 'to-do-c2aee',
    authDomain: 'to-do-c2aee.firebaseapp.com',
    storageBucket: 'to-do-c2aee.appspot.com',
  );
}
